name: CI
on:
  pull_request:
  push:
    branches:
      - main
env:
  RUST_BACKTRACE: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v12
      with:
        name: derecho-dev
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build shell.nix
    - run: nix-shell --run "cargo test --all"